//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abbey.PdfProcessor.PremiumTransactionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PdfBonusTransaction", Namespace="http://www.outsystems.com")]
    [System.SerializableAttribute()]
    public partial class PdfBonusTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IdField;
        
        private long AgencyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatementGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatementContractNumberField;
        
        private string StatementDateField;
        
        private decimal DisbursementAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyProducerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProducerContractNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyNumberField;
        
        private string TransactionDateField;
        
        private decimal AmountField;
        
        private decimal ExcessAmountField;
        
        private decimal PaidToBGAField;
        
        private string StagedDateField;
        
        private string ImportDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatchedPolicyNumberField;
        
        private decimal UnappliedAmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long AgencyId {
            get {
                return this.AgencyIdField;
            }
            set {
                if ((this.AgencyIdField.Equals(value) != true)) {
                    this.AgencyIdField = value;
                    this.RaisePropertyChanged("AgencyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StatementGuid {
            get {
                return this.StatementGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.StatementGuidField, value) != true)) {
                    this.StatementGuidField = value;
                    this.RaisePropertyChanged("StatementGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StatementContractNumber {
            get {
                return this.StatementContractNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.StatementContractNumberField, value) != true)) {
                    this.StatementContractNumberField = value;
                    this.RaisePropertyChanged("StatementContractNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string StatementDate {
            get {
                return this.StatementDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StatementDateField, value) != true)) {
                    this.StatementDateField = value;
                    this.RaisePropertyChanged("StatementDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal DisbursementAmount {
            get {
                return this.DisbursementAmountField;
            }
            set {
                if ((this.DisbursementAmountField.Equals(value) != true)) {
                    this.DisbursementAmountField = value;
                    this.RaisePropertyChanged("DisbursementAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string PolicyProducer {
            get {
                return this.PolicyProducerField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyProducerField, value) != true)) {
                    this.PolicyProducerField = value;
                    this.RaisePropertyChanged("PolicyProducer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ProducerContractNumber {
            get {
                return this.ProducerContractNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ProducerContractNumberField, value) != true)) {
                    this.ProducerContractNumberField = value;
                    this.RaisePropertyChanged("ProducerContractNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string PolicyNumber {
            get {
                return this.PolicyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyNumberField, value) != true)) {
                    this.PolicyNumberField = value;
                    this.RaisePropertyChanged("PolicyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=9)]
        public string TransactionDate {
            get {
                return this.TransactionDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionDateField, value) != true)) {
                    this.TransactionDateField = value;
                    this.RaisePropertyChanged("TransactionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public decimal ExcessAmount {
            get {
                return this.ExcessAmountField;
            }
            set {
                if ((this.ExcessAmountField.Equals(value) != true)) {
                    this.ExcessAmountField = value;
                    this.RaisePropertyChanged("ExcessAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public decimal PaidToBGA {
            get {
                return this.PaidToBGAField;
            }
            set {
                if ((this.PaidToBGAField.Equals(value) != true)) {
                    this.PaidToBGAField = value;
                    this.RaisePropertyChanged("PaidToBGA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=13)]
        public string StagedDate {
            get {
                return this.StagedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StagedDateField, value) != true)) {
                    this.StagedDateField = value;
                    this.RaisePropertyChanged("StagedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=14)]
        public string ImportDate {
            get {
                return this.ImportDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportDateField, value) != true)) {
                    this.ImportDateField = value;
                    this.RaisePropertyChanged("ImportDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string MatchedPolicyNumber {
            get {
                return this.MatchedPolicyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchedPolicyNumberField, value) != true)) {
                    this.MatchedPolicyNumberField = value;
                    this.RaisePropertyChanged("MatchedPolicyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public decimal UnappliedAmount {
            get {
                return this.UnappliedAmountField;
            }
            set {
                if ((this.UnappliedAmountField.Equals(value) != true)) {
                    this.UnappliedAmountField = value;
                    this.RaisePropertyChanged("UnappliedAmount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StagedPremiumTransaction", Namespace="http://www.outsystems.com")]
    [System.SerializableAttribute()]
    public partial class StagedPremiumTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyNumberField;
        
        private string DueDateField;
        
        private decimal AmountField;
        
        private decimal ExcessAmountField;
        
        private string TransactionDateField;
        
        private string StatementDateField;
        
        private string StagedDateField;
        
        private string ImportDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatementGuidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PolicyNumber {
            get {
                return this.PolicyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyNumberField, value) != true)) {
                    this.PolicyNumberField = value;
                    this.RaisePropertyChanged("PolicyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DueDateField, value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal ExcessAmount {
            get {
                return this.ExcessAmountField;
            }
            set {
                if ((this.ExcessAmountField.Equals(value) != true)) {
                    this.ExcessAmountField = value;
                    this.RaisePropertyChanged("ExcessAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string TransactionDate {
            get {
                return this.TransactionDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionDateField, value) != true)) {
                    this.TransactionDateField = value;
                    this.RaisePropertyChanged("TransactionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public string StatementDate {
            get {
                return this.StatementDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StatementDateField, value) != true)) {
                    this.StatementDateField = value;
                    this.RaisePropertyChanged("StatementDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public string StagedDate {
            get {
                return this.StagedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StagedDateField, value) != true)) {
                    this.StagedDateField = value;
                    this.RaisePropertyChanged("StagedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=8)]
        public string ImportDate {
            get {
                return this.ImportDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportDateField, value) != true)) {
                    this.ImportDateField = value;
                    this.RaisePropertyChanged("ImportDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string AgentName {
            get {
                return this.AgentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentNameField, value) != true)) {
                    this.AgentNameField = value;
                    this.RaisePropertyChanged("AgentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string StatementGuid {
            get {
                return this.StatementGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.StatementGuidField, value) != true)) {
                    this.StatementGuidField = value;
                    this.RaisePropertyChanged("StatementGuid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PdfPremiumTransaction", Namespace="http://www.outsystems.com")]
    [System.SerializableAttribute()]
    public partial class PdfPremiumTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IdField;
        
        private long AgencyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatementGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatementContractNumberField;
        
        private string StatementDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatementProducerField;
        
        private decimal DisbursementAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyProducerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProducerContractNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyNumberField;
        
        private string TransactionDateField;
        
        private decimal AmountField;
        
        private decimal ExcessAmountField;
        
        private decimal PaidToProducerField;
        
        private decimal PaidToBGAField;
        
        private string StagedDateField;
        
        private string ImportDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatchedPolicyNumberField;
        
        private string EffectiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InsuredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssueStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeField;
        
        private string PaidToDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long AgencyId {
            get {
                return this.AgencyIdField;
            }
            set {
                if ((this.AgencyIdField.Equals(value) != true)) {
                    this.AgencyIdField = value;
                    this.RaisePropertyChanged("AgencyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string StatementGuid {
            get {
                return this.StatementGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.StatementGuidField, value) != true)) {
                    this.StatementGuidField = value;
                    this.RaisePropertyChanged("StatementGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StatementContractNumber {
            get {
                return this.StatementContractNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.StatementContractNumberField, value) != true)) {
                    this.StatementContractNumberField = value;
                    this.RaisePropertyChanged("StatementContractNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string StatementDate {
            get {
                return this.StatementDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StatementDateField, value) != true)) {
                    this.StatementDateField = value;
                    this.RaisePropertyChanged("StatementDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string StatementProducer {
            get {
                return this.StatementProducerField;
            }
            set {
                if ((object.ReferenceEquals(this.StatementProducerField, value) != true)) {
                    this.StatementProducerField = value;
                    this.RaisePropertyChanged("StatementProducer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal DisbursementAmount {
            get {
                return this.DisbursementAmountField;
            }
            set {
                if ((this.DisbursementAmountField.Equals(value) != true)) {
                    this.DisbursementAmountField = value;
                    this.RaisePropertyChanged("DisbursementAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PolicyProducer {
            get {
                return this.PolicyProducerField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyProducerField, value) != true)) {
                    this.PolicyProducerField = value;
                    this.RaisePropertyChanged("PolicyProducer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ProducerContractNumber {
            get {
                return this.ProducerContractNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ProducerContractNumberField, value) != true)) {
                    this.ProducerContractNumberField = value;
                    this.RaisePropertyChanged("ProducerContractNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string PolicyNumber {
            get {
                return this.PolicyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyNumberField, value) != true)) {
                    this.PolicyNumberField = value;
                    this.RaisePropertyChanged("PolicyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=10)]
        public string TransactionDate {
            get {
                return this.TransactionDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionDateField, value) != true)) {
                    this.TransactionDateField = value;
                    this.RaisePropertyChanged("TransactionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public decimal ExcessAmount {
            get {
                return this.ExcessAmountField;
            }
            set {
                if ((this.ExcessAmountField.Equals(value) != true)) {
                    this.ExcessAmountField = value;
                    this.RaisePropertyChanged("ExcessAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public decimal PaidToProducer {
            get {
                return this.PaidToProducerField;
            }
            set {
                if ((this.PaidToProducerField.Equals(value) != true)) {
                    this.PaidToProducerField = value;
                    this.RaisePropertyChanged("PaidToProducer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public decimal PaidToBGA {
            get {
                return this.PaidToBGAField;
            }
            set {
                if ((this.PaidToBGAField.Equals(value) != true)) {
                    this.PaidToBGAField = value;
                    this.RaisePropertyChanged("PaidToBGA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=15)]
        public string StagedDate {
            get {
                return this.StagedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StagedDateField, value) != true)) {
                    this.StagedDateField = value;
                    this.RaisePropertyChanged("StagedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=16)]
        public string ImportDate {
            get {
                return this.ImportDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportDateField, value) != true)) {
                    this.ImportDateField = value;
                    this.RaisePropertyChanged("ImportDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string MatchedPolicyNumber {
            get {
                return this.MatchedPolicyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchedPolicyNumberField, value) != true)) {
                    this.MatchedPolicyNumberField = value;
                    this.RaisePropertyChanged("MatchedPolicyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=18)]
        public string EffectiveDate {
            get {
                return this.EffectiveDateField;
            }
            set {
                if ((object.ReferenceEquals(this.EffectiveDateField, value) != true)) {
                    this.EffectiveDateField = value;
                    this.RaisePropertyChanged("EffectiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Insured {
            get {
                return this.InsuredField;
            }
            set {
                if ((object.ReferenceEquals(this.InsuredField, value) != true)) {
                    this.InsuredField = value;
                    this.RaisePropertyChanged("Insured");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string IssueState {
            get {
                return this.IssueStateField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueStateField, value) != true)) {
                    this.IssueStateField = value;
                    this.RaisePropertyChanged("IssueState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeField, value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=23)]
        public string PaidToDate {
            get {
                return this.PaidToDateField;
            }
            set {
                if ((object.ReferenceEquals(this.PaidToDateField, value) != true)) {
                    this.PaidToDateField = value;
                    this.RaisePropertyChanged("PaidToDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://CommissionPortalTesting/PremiumTransactionService/", ConfigurationName="PremiumTransactionService.PremiumTransactionServiceSoap")]
    public interface PremiumTransactionServiceSoap {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.outsystems.com) of message StorePdfBonusTransactionRequest does not match the default value (http://CommissionPortalTesting/PremiumTransactionService/)
        [System.ServiceModel.OperationContractAttribute(Action="http://CommissionPortalTesting/PremiumTransactionService/StorePdfBonusTransaction" +
            "", ReplyAction="*")]
        Abbey.PdfProcessor.PremiumTransactionService.StorePdfBonusTransactionResponse StorePdfBonusTransaction(Abbey.PdfProcessor.PremiumTransactionService.StorePdfBonusTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CommissionPortalTesting/PremiumTransactionService/StorePdfBonusTransaction" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<Abbey.PdfProcessor.PremiumTransactionService.StorePdfBonusTransactionResponse> StorePdfBonusTransactionAsync(Abbey.PdfProcessor.PremiumTransactionService.StorePdfBonusTransactionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.outsystems.com) of message ProcessTransactionRequest does not match the default value (http://CommissionPortalTesting/PremiumTransactionService/)
        [System.ServiceModel.OperationContractAttribute(Action="http://CommissionPortalTesting/PremiumTransactionService/ProcessTransaction", ReplyAction="*")]
        Abbey.PdfProcessor.PremiumTransactionService.ProcessTransactionResponse ProcessTransaction(Abbey.PdfProcessor.PremiumTransactionService.ProcessTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CommissionPortalTesting/PremiumTransactionService/ProcessTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<Abbey.PdfProcessor.PremiumTransactionService.ProcessTransactionResponse> ProcessTransactionAsync(Abbey.PdfProcessor.PremiumTransactionService.ProcessTransactionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.outsystems.com) of message StorePdfDepositRequest does not match the default value (http://CommissionPortalTesting/PremiumTransactionService/)
        [System.ServiceModel.OperationContractAttribute(Action="http://CommissionPortalTesting/PremiumTransactionService/StorePdfDeposit", ReplyAction="*")]
        Abbey.PdfProcessor.PremiumTransactionService.StorePdfDepositResponse StorePdfDeposit(Abbey.PdfProcessor.PremiumTransactionService.StorePdfDepositRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CommissionPortalTesting/PremiumTransactionService/StorePdfDeposit", ReplyAction="*")]
        System.Threading.Tasks.Task<Abbey.PdfProcessor.PremiumTransactionService.StorePdfDepositResponse> StorePdfDepositAsync(Abbey.PdfProcessor.PremiumTransactionService.StorePdfDepositRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.outsystems.com) of message StorePDFRequest does not match the default value (http://CommissionPortalTesting/PremiumTransactionService/)
        [System.ServiceModel.OperationContractAttribute(Action="http://CommissionPortalTesting/PremiumTransactionService/StorePDF", ReplyAction="*")]
        Abbey.PdfProcessor.PremiumTransactionService.StorePDFResponse StorePDF(Abbey.PdfProcessor.PremiumTransactionService.StorePDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CommissionPortalTesting/PremiumTransactionService/StorePDF", ReplyAction="*")]
        System.Threading.Tasks.Task<Abbey.PdfProcessor.PremiumTransactionService.StorePDFResponse> StorePDFAsync(Abbey.PdfProcessor.PremiumTransactionService.StorePDFRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.outsystems.com) of message WipeStagedTransactionsRequest does not match the default value (http://CommissionPortalTesting/PremiumTransactionService/)
        [System.ServiceModel.OperationContractAttribute(Action="http://CommissionPortalTesting/PremiumTransactionService/WipeStagedTransactions", ReplyAction="*")]
        Abbey.PdfProcessor.PremiumTransactionService.WipeStagedTransactionsResponse WipeStagedTransactions(Abbey.PdfProcessor.PremiumTransactionService.WipeStagedTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CommissionPortalTesting/PremiumTransactionService/WipeStagedTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<Abbey.PdfProcessor.PremiumTransactionService.WipeStagedTransactionsResponse> WipeStagedTransactionsAsync(Abbey.PdfProcessor.PremiumTransactionService.WipeStagedTransactionsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.outsystems.com) of message StorePdfTransactionRequest does not match the default value (http://CommissionPortalTesting/PremiumTransactionService/)
        [System.ServiceModel.OperationContractAttribute(Action="http://CommissionPortalTesting/PremiumTransactionService/StorePdfTransaction", ReplyAction="*")]
        Abbey.PdfProcessor.PremiumTransactionService.StorePdfTransactionResponse StorePdfTransaction(Abbey.PdfProcessor.PremiumTransactionService.StorePdfTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CommissionPortalTesting/PremiumTransactionService/StorePdfTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<Abbey.PdfProcessor.PremiumTransactionService.StorePdfTransactionResponse> StorePdfTransactionAsync(Abbey.PdfProcessor.PremiumTransactionService.StorePdfTransactionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StorePdfBonusTransaction", WrapperNamespace="http://www.outsystems.com", IsWrapped=true)]
    public partial class StorePdfBonusTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.outsystems.com", Order=0)]
        public long AgencyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.outsystems.com", Order=1)]
        public string CarrierName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.outsystems.com", Order=2)]
        public Abbey.PdfProcessor.PremiumTransactionService.PdfBonusTransaction NewPdfBonusTransaction;
        
        public StorePdfBonusTransactionRequest() {
        }
        
        public StorePdfBonusTransactionRequest(long AgencyId, string CarrierName, Abbey.PdfProcessor.PremiumTransactionService.PdfBonusTransaction NewPdfBonusTransaction) {
            this.AgencyId = AgencyId;
            this.CarrierName = CarrierName;
            this.NewPdfBonusTransaction = NewPdfBonusTransaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StorePdfBonusTransactionResponse", WrapperNamespace="http://www.outsystems.com", IsWrapped=true)]
    public partial class StorePdfBonusTransactionResponse {
        
        public StorePdfBonusTransactionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessTransaction", WrapperNamespace="http://www.outsystems.com", IsWrapped=true)]
    public partial class ProcessTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.outsystems.com", Order=0)]
        public string CarrierName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.outsystems.com", Order=1)]
        public Abbey.PdfProcessor.PremiumTransactionService.StagedPremiumTransaction NewPremiumTransaction;
        
        public ProcessTransactionRequest() {
        }
        
        public ProcessTransactionRequest(string CarrierName, Abbey.PdfProcessor.PremiumTransactionService.StagedPremiumTransaction NewPremiumTransaction) {
            this.CarrierName = CarrierName;
            this.NewPremiumTransaction = NewPremiumTransaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessTransactionResponse", WrapperNamespace="http://www.outsystems.com", IsWrapped=true)]
    public partial class ProcessTransactionResponse {
        
        public ProcessTransactionResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StorePdfDeposit", WrapperNamespace="http://www.outsystems.com", IsWrapped=true)]
    public partial class StorePdfDepositRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.outsystems.com", Order=0)]
        public long AgencyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.outsystems.com", Order=1)]
        public Abbey.PdfProcessor.PremiumTransactionService.PdfPremiumTransaction NewPdfPremiumTransaction;
        
        public StorePdfDepositRequest() {
        }
        
        public StorePdfDepositRequest(long AgencyId, Abbey.PdfProcessor.PremiumTransactionService.PdfPremiumTransaction NewPdfPremiumTransaction) {
            this.AgencyId = AgencyId;
            this.NewPdfPremiumTransaction = NewPdfPremiumTransaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StorePdfDepositResponse", WrapperNamespace="http://www.outsystems.com", IsWrapped=true)]
    public partial class StorePdfDepositResponse {
        
        public StorePdfDepositResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StorePDF", WrapperNamespace="http://www.outsystems.com", IsWrapped=true)]
    public partial class StorePDFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.outsystems.com", Order=0)]
        public long AgencyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.outsystems.com", Order=1)]
        public string CarrierName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.outsystems.com", Order=2)]
        public string StatementGuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.outsystems.com", Order=3)]
        public string PDFBase64Content;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.outsystems.com", Order=4)]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.outsystems.com", Order=5)]
        public bool IsBonus;
        
        public StorePDFRequest() {
        }
        
        public StorePDFRequest(long AgencyId, string CarrierName, string StatementGuid, string PDFBase64Content, string FileName, bool IsBonus) {
            this.AgencyId = AgencyId;
            this.CarrierName = CarrierName;
            this.StatementGuid = StatementGuid;
            this.PDFBase64Content = PDFBase64Content;
            this.FileName = FileName;
            this.IsBonus = IsBonus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StorePDFResponse", WrapperNamespace="http://www.outsystems.com", IsWrapped=true)]
    public partial class StorePDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.outsystems.com", Order=0)]
        public string ParsedCarrierStatementGuid;
        
        public StorePDFResponse() {
        }
        
        public StorePDFResponse(string ParsedCarrierStatementGuid) {
            this.ParsedCarrierStatementGuid = ParsedCarrierStatementGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WipeStagedTransactions", WrapperNamespace="http://www.outsystems.com", IsWrapped=true)]
    public partial class WipeStagedTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.outsystems.com", Order=0)]
        public long AgencyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.outsystems.com", Order=1)]
        public string CarrierName;
        
        public WipeStagedTransactionsRequest() {
        }
        
        public WipeStagedTransactionsRequest(long AgencyId, string CarrierName) {
            this.AgencyId = AgencyId;
            this.CarrierName = CarrierName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WipeStagedTransactionsResponse", WrapperNamespace="http://www.outsystems.com", IsWrapped=true)]
    public partial class WipeStagedTransactionsResponse {
        
        public WipeStagedTransactionsResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StorePdfTransaction", WrapperNamespace="http://www.outsystems.com", IsWrapped=true)]
    public partial class StorePdfTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.outsystems.com", Order=0)]
        public long AgencyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.outsystems.com", Order=1)]
        public string CarrierName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.outsystems.com", Order=2)]
        public Abbey.PdfProcessor.PremiumTransactionService.PdfPremiumTransaction NewPdfPremiumTransaction;
        
        public StorePdfTransactionRequest() {
        }
        
        public StorePdfTransactionRequest(long AgencyId, string CarrierName, Abbey.PdfProcessor.PremiumTransactionService.PdfPremiumTransaction NewPdfPremiumTransaction) {
            this.AgencyId = AgencyId;
            this.CarrierName = CarrierName;
            this.NewPdfPremiumTransaction = NewPdfPremiumTransaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StorePdfTransactionResponse", WrapperNamespace="http://www.outsystems.com", IsWrapped=true)]
    public partial class StorePdfTransactionResponse {
        
        public StorePdfTransactionResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PremiumTransactionServiceSoapChannel : Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PremiumTransactionServiceSoapClient : System.ServiceModel.ClientBase<Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap>, Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap {
        
        public PremiumTransactionServiceSoapClient() {
        }
        
        public PremiumTransactionServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PremiumTransactionServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PremiumTransactionServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PremiumTransactionServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Abbey.PdfProcessor.PremiumTransactionService.StorePdfBonusTransactionResponse Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap.StorePdfBonusTransaction(Abbey.PdfProcessor.PremiumTransactionService.StorePdfBonusTransactionRequest request) {
            return base.Channel.StorePdfBonusTransaction(request);
        }
        
        public void StorePdfBonusTransaction(long AgencyId, string CarrierName, Abbey.PdfProcessor.PremiumTransactionService.PdfBonusTransaction NewPdfBonusTransaction) {
            Abbey.PdfProcessor.PremiumTransactionService.StorePdfBonusTransactionRequest inValue = new Abbey.PdfProcessor.PremiumTransactionService.StorePdfBonusTransactionRequest();
            inValue.AgencyId = AgencyId;
            inValue.CarrierName = CarrierName;
            inValue.NewPdfBonusTransaction = NewPdfBonusTransaction;
            Abbey.PdfProcessor.PremiumTransactionService.StorePdfBonusTransactionResponse retVal = ((Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap)(this)).StorePdfBonusTransaction(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Abbey.PdfProcessor.PremiumTransactionService.StorePdfBonusTransactionResponse> Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap.StorePdfBonusTransactionAsync(Abbey.PdfProcessor.PremiumTransactionService.StorePdfBonusTransactionRequest request) {
            return base.Channel.StorePdfBonusTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Abbey.PdfProcessor.PremiumTransactionService.StorePdfBonusTransactionResponse> StorePdfBonusTransactionAsync(long AgencyId, string CarrierName, Abbey.PdfProcessor.PremiumTransactionService.PdfBonusTransaction NewPdfBonusTransaction) {
            Abbey.PdfProcessor.PremiumTransactionService.StorePdfBonusTransactionRequest inValue = new Abbey.PdfProcessor.PremiumTransactionService.StorePdfBonusTransactionRequest();
            inValue.AgencyId = AgencyId;
            inValue.CarrierName = CarrierName;
            inValue.NewPdfBonusTransaction = NewPdfBonusTransaction;
            return ((Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap)(this)).StorePdfBonusTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Abbey.PdfProcessor.PremiumTransactionService.ProcessTransactionResponse Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap.ProcessTransaction(Abbey.PdfProcessor.PremiumTransactionService.ProcessTransactionRequest request) {
            return base.Channel.ProcessTransaction(request);
        }
        
        public void ProcessTransaction(string CarrierName, Abbey.PdfProcessor.PremiumTransactionService.StagedPremiumTransaction NewPremiumTransaction) {
            Abbey.PdfProcessor.PremiumTransactionService.ProcessTransactionRequest inValue = new Abbey.PdfProcessor.PremiumTransactionService.ProcessTransactionRequest();
            inValue.CarrierName = CarrierName;
            inValue.NewPremiumTransaction = NewPremiumTransaction;
            Abbey.PdfProcessor.PremiumTransactionService.ProcessTransactionResponse retVal = ((Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap)(this)).ProcessTransaction(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Abbey.PdfProcessor.PremiumTransactionService.ProcessTransactionResponse> Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap.ProcessTransactionAsync(Abbey.PdfProcessor.PremiumTransactionService.ProcessTransactionRequest request) {
            return base.Channel.ProcessTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Abbey.PdfProcessor.PremiumTransactionService.ProcessTransactionResponse> ProcessTransactionAsync(string CarrierName, Abbey.PdfProcessor.PremiumTransactionService.StagedPremiumTransaction NewPremiumTransaction) {
            Abbey.PdfProcessor.PremiumTransactionService.ProcessTransactionRequest inValue = new Abbey.PdfProcessor.PremiumTransactionService.ProcessTransactionRequest();
            inValue.CarrierName = CarrierName;
            inValue.NewPremiumTransaction = NewPremiumTransaction;
            return ((Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap)(this)).ProcessTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Abbey.PdfProcessor.PremiumTransactionService.StorePdfDepositResponse Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap.StorePdfDeposit(Abbey.PdfProcessor.PremiumTransactionService.StorePdfDepositRequest request) {
            return base.Channel.StorePdfDeposit(request);
        }
        
        public void StorePdfDeposit(long AgencyId, Abbey.PdfProcessor.PremiumTransactionService.PdfPremiumTransaction NewPdfPremiumTransaction) {
            Abbey.PdfProcessor.PremiumTransactionService.StorePdfDepositRequest inValue = new Abbey.PdfProcessor.PremiumTransactionService.StorePdfDepositRequest();
            inValue.AgencyId = AgencyId;
            inValue.NewPdfPremiumTransaction = NewPdfPremiumTransaction;
            Abbey.PdfProcessor.PremiumTransactionService.StorePdfDepositResponse retVal = ((Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap)(this)).StorePdfDeposit(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Abbey.PdfProcessor.PremiumTransactionService.StorePdfDepositResponse> Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap.StorePdfDepositAsync(Abbey.PdfProcessor.PremiumTransactionService.StorePdfDepositRequest request) {
            return base.Channel.StorePdfDepositAsync(request);
        }
        
        public System.Threading.Tasks.Task<Abbey.PdfProcessor.PremiumTransactionService.StorePdfDepositResponse> StorePdfDepositAsync(long AgencyId, Abbey.PdfProcessor.PremiumTransactionService.PdfPremiumTransaction NewPdfPremiumTransaction) {
            Abbey.PdfProcessor.PremiumTransactionService.StorePdfDepositRequest inValue = new Abbey.PdfProcessor.PremiumTransactionService.StorePdfDepositRequest();
            inValue.AgencyId = AgencyId;
            inValue.NewPdfPremiumTransaction = NewPdfPremiumTransaction;
            return ((Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap)(this)).StorePdfDepositAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Abbey.PdfProcessor.PremiumTransactionService.StorePDFResponse Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap.StorePDF(Abbey.PdfProcessor.PremiumTransactionService.StorePDFRequest request) {
            return base.Channel.StorePDF(request);
        }
        
        public string StorePDF(long AgencyId, string CarrierName, string StatementGuid, string PDFBase64Content, string FileName, bool IsBonus) {
            Abbey.PdfProcessor.PremiumTransactionService.StorePDFRequest inValue = new Abbey.PdfProcessor.PremiumTransactionService.StorePDFRequest();
            inValue.AgencyId = AgencyId;
            inValue.CarrierName = CarrierName;
            inValue.StatementGuid = StatementGuid;
            inValue.PDFBase64Content = PDFBase64Content;
            inValue.FileName = FileName;
            inValue.IsBonus = IsBonus;
            Abbey.PdfProcessor.PremiumTransactionService.StorePDFResponse retVal = ((Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap)(this)).StorePDF(inValue);
            return retVal.ParsedCarrierStatementGuid;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Abbey.PdfProcessor.PremiumTransactionService.StorePDFResponse> Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap.StorePDFAsync(Abbey.PdfProcessor.PremiumTransactionService.StorePDFRequest request) {
            return base.Channel.StorePDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<Abbey.PdfProcessor.PremiumTransactionService.StorePDFResponse> StorePDFAsync(long AgencyId, string CarrierName, string StatementGuid, string PDFBase64Content, string FileName, bool IsBonus) {
            Abbey.PdfProcessor.PremiumTransactionService.StorePDFRequest inValue = new Abbey.PdfProcessor.PremiumTransactionService.StorePDFRequest();
            inValue.AgencyId = AgencyId;
            inValue.CarrierName = CarrierName;
            inValue.StatementGuid = StatementGuid;
            inValue.PDFBase64Content = PDFBase64Content;
            inValue.FileName = FileName;
            inValue.IsBonus = IsBonus;
            return ((Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap)(this)).StorePDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Abbey.PdfProcessor.PremiumTransactionService.WipeStagedTransactionsResponse Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap.WipeStagedTransactions(Abbey.PdfProcessor.PremiumTransactionService.WipeStagedTransactionsRequest request) {
            return base.Channel.WipeStagedTransactions(request);
        }
        
        public void WipeStagedTransactions(long AgencyId, string CarrierName) {
            Abbey.PdfProcessor.PremiumTransactionService.WipeStagedTransactionsRequest inValue = new Abbey.PdfProcessor.PremiumTransactionService.WipeStagedTransactionsRequest();
            inValue.AgencyId = AgencyId;
            inValue.CarrierName = CarrierName;
            Abbey.PdfProcessor.PremiumTransactionService.WipeStagedTransactionsResponse retVal = ((Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap)(this)).WipeStagedTransactions(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Abbey.PdfProcessor.PremiumTransactionService.WipeStagedTransactionsResponse> Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap.WipeStagedTransactionsAsync(Abbey.PdfProcessor.PremiumTransactionService.WipeStagedTransactionsRequest request) {
            return base.Channel.WipeStagedTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Abbey.PdfProcessor.PremiumTransactionService.WipeStagedTransactionsResponse> WipeStagedTransactionsAsync(long AgencyId, string CarrierName) {
            Abbey.PdfProcessor.PremiumTransactionService.WipeStagedTransactionsRequest inValue = new Abbey.PdfProcessor.PremiumTransactionService.WipeStagedTransactionsRequest();
            inValue.AgencyId = AgencyId;
            inValue.CarrierName = CarrierName;
            return ((Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap)(this)).WipeStagedTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Abbey.PdfProcessor.PremiumTransactionService.StorePdfTransactionResponse Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap.StorePdfTransaction(Abbey.PdfProcessor.PremiumTransactionService.StorePdfTransactionRequest request) {
            return base.Channel.StorePdfTransaction(request);
        }
        
        public void StorePdfTransaction(long AgencyId, string CarrierName, Abbey.PdfProcessor.PremiumTransactionService.PdfPremiumTransaction NewPdfPremiumTransaction) {
            Abbey.PdfProcessor.PremiumTransactionService.StorePdfTransactionRequest inValue = new Abbey.PdfProcessor.PremiumTransactionService.StorePdfTransactionRequest();
            inValue.AgencyId = AgencyId;
            inValue.CarrierName = CarrierName;
            inValue.NewPdfPremiumTransaction = NewPdfPremiumTransaction;
            Abbey.PdfProcessor.PremiumTransactionService.StorePdfTransactionResponse retVal = ((Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap)(this)).StorePdfTransaction(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Abbey.PdfProcessor.PremiumTransactionService.StorePdfTransactionResponse> Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap.StorePdfTransactionAsync(Abbey.PdfProcessor.PremiumTransactionService.StorePdfTransactionRequest request) {
            return base.Channel.StorePdfTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Abbey.PdfProcessor.PremiumTransactionService.StorePdfTransactionResponse> StorePdfTransactionAsync(long AgencyId, string CarrierName, Abbey.PdfProcessor.PremiumTransactionService.PdfPremiumTransaction NewPdfPremiumTransaction) {
            Abbey.PdfProcessor.PremiumTransactionService.StorePdfTransactionRequest inValue = new Abbey.PdfProcessor.PremiumTransactionService.StorePdfTransactionRequest();
            inValue.AgencyId = AgencyId;
            inValue.CarrierName = CarrierName;
            inValue.NewPdfPremiumTransaction = NewPdfPremiumTransaction;
            return ((Abbey.PdfProcessor.PremiumTransactionService.PremiumTransactionServiceSoap)(this)).StorePdfTransactionAsync(inValue);
        }
    }
}
